-- liquibase formatted sql

-- changeset Sergalas:1770788690087-1
CREATE TABLE user_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id    BIGINT NULL,
    locale     VARCHAR(255) NULL,
    first_name VARCHAR(255) NULL,
    CONSTRAINT pk_user_session PRIMARY KEY (id)
);

